<a href="https://colab.research.google.com/github/varunsmhatre/TF-Developer/blob/main/Regression/Boston_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
tf.__version__

'2.8.0'

#Load Dataset

In [ ]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.boston_housing.load_data(
    path='boston_housing.npz', test_split=0.2, seed=113
)

65536/57026 [==================================] - 0s 0us/step


In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((404, 13), (404,), (102, 13), (102,))

In [ ]:
X_train[0], y_train[0]

(array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
         91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
         18.72   ]), 15.2)

In [ ]:
tf.linalg.normalize(
    tf.constant([1, 2, 3, 100], dtype=tf.float16), ord='euclidean', axis=0
)

(<tf.Tensor: shape=(4,), dtype=float16, numpy=array([0.009995, 0.01999 , 0.02998 , 0.9995  ], dtype=float16)>,
 <tf.Tensor: shape=(1,), dtype=float16, numpy=array([100.06], dtype=float16)>)

## Train the model

In [84]:
tf.random.set_seed(42)

# Add an extra layer and increase number of units
model_1 = tf.keras.Sequential([
  # tf.keras.layers.Dense(100, activation=tf.keras.activations.relu), # 100 units
  # tf.keras.layers.Dense(100, activation=tf.keras.activations.relu), # 10 units
  tf.keras.layers.Dense(10, activation=tf.keras.activations.relu), # 1 unit (important for output layer)
  tf.keras.layers.Dense(1), # 1 unit (important for output layer)

])

# Compile the model
model_1.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), # Adam works but SGD doesn't 
                          metrics=['mae', 'mse'])


# Fit the model and save the history (we can plot this)
history_1 = model_1.fit(X_train, y_train, epochs=100, verbose=0)
model_1.evaluate(X_test, y_test)

4/4 [==============================] - 0s 4ms/step - loss: 4.1909 - mae: 4.1909 - mse: 37.5711


[4.190866947174072, 4.190866947174072, 37.571136474609375]